In [ ]:
#Import libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
df = pd.read_csv('Reviews.csv', nrows=50000)
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...
...,...,...,...,...,...,...,...,...,...,...
49995,49996,B00430B73W,AKW867T7C6HF8,HWJ3,0,0,5,1261180800,Grown to really like them,My sister introduced me to these. They have be...
49996,49997,B00430B73W,A2PEHNEDMHOYTW,L. Allen,0,0,5,1258934400,Healthy Snack at a great price!,A friend recommended these bars and I fell in ...
49997,49998,B00430B73W,A2QH2KF2IAB143,"J. A. Meyers ""Jan""",0,0,5,1257379200,Raw Revolution Hazelnut Cashew,Fabulous! I take one to work with me every da...
49998,49999,B00430B73W,AMX286UGXISMA,Aaron Dragushan,0,0,4,1247702400,"fantastic, but chew carefully",I love these bars and will continue to buy the...


In [ ]:
#Text Selection
df = pd.read_csv('Reviews.csv', nrows=50000)
print(" Dataset loaded successfully!")
print(f"Shape: {df.shape}")
print(df[['Text', 'Score']].head(3))

 Dataset loaded successfully!
Shape: (50000, 10)
                                                Text  Score
0  I have bought several of the Vitality canned d...      5
1  Product arrived labeled as Jumbo Salted Peanut...      1
2  This is a confection that has been around a fe...      4


In [ ]:
#Vectorization Engine
sentence_1 = "This olive oil is wonderful and very light on the stomach."
sentence_2 = "The packaging was broken and let too much light inside the box."
sentence_3 = "I prefer this brand because it is a light and healthy snack."
sentences = [sentence_1, sentence_2, sentence_3]
print(" Sentences:")
for i, s in enumerate(sentences, 1):
    print(f"  Sentence {i}: {s}")

 Sentences:
  Sentence 1: This olive oil is wonderful and very light on the stomach.
  Sentence 2: The packaging was broken and let too much light inside the box.
  Sentence 3: I prefer this brand because it is a light and healthy snack.


In [ ]:
#Vector Slicing
vectorizer = CountVectorizer()
dtm = vectorizer.fit_transform(sentences)
dense_matrix = dtm.toarray()
print(" Vocabulary:")
print(vectorizer.get_feature_names_out())
print()
print(" Document-Term Matrix (dense NumPy array):")
print(dense_matrix)
print(f"\nMatrix shape: {dense_matrix.shape}  →  (3 sentences × {dense_matrix.shape[1]} unique words)")

 Vocabulary:
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']

 Document-Term Matrix (dense NumPy array):
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]

Matrix shape: (3, 25)  →  (3 sentences × 25 unique words)


In [ ]:
#Similarity Mathematics (Dot Product)
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]
print("vec_1 → Sentence 1 (light = texture/calorie):")
print(vec_1)
print("\nvec_2 → Sentence 2 (light = illumination):")
print(vec_2)
print("\nvec_3 → Sentence 3 (light = calorie/weight):")
print(vec_3)

vec_1 → Sentence 1 (light = texture/calorie):
[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]

vec_2 → Sentence 2 (light = illumination):
[1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]

vec_3 → Sentence 3 (light = calorie/weight):
[1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [ ]:
similarity_1_2 = np.dot(vec_1, vec_2)
similarity_1_3 = np.dot(vec_1, vec_3)
print("=" * 55)
print("         DOT PRODUCT SIMILARITY SCORES")
print("=" * 55)
print(f"  S1 vs S2 (Different contexts — light meaning differs): {similarity_1_2}")
print(f"  S1 vs S3 (Similar contexts  — light means same thing): {similarity_1_3}")
print("=" * 55)

         DOT PRODUCT SIMILARITY SCORES
  S1 vs S2 (Different contexts — light meaning differs): 4
  S1 vs S3 (Similar contexts  — light means same thing): 4


In [ ]:
#Final Summary & Analysis
print("\n========== FINAL RESULTS SUMMARY ==========\n")
print(f'Sentence 1: "{sentence_1}"')
print(f'Sentence 2: "{sentence_2}"')
print(f'Sentence 3: "{sentence_3}"')
print(f"\n Dot Product (S1 vs S2) [Different Context]: {similarity_1_2}")
print(f" Dot Product (S1 vs S3) [Same Context]:      {similarity_1_3}")
print("\n KEY INSIGHT:")
print("   BoW assigns identical weight to 'light' in all sentences.")
print("   It cannot distinguish 'light' (illumination) from")
print("   'light' (low-calorie) — proving the Polysemy Barrier.")
print("\n Static count vectors fail to capture word meaning in context.")


========== FINAL RESULTS SUMMARY ==========

Sentence 1: "This olive oil is wonderful and very light on the stomach."
Sentence 2: "The packaging was broken and let too much light inside the box."
Sentence 3: "I prefer this brand because it is a light and healthy snack."

 Dot Product (S1 vs S2) [Different Context]: 4
 Dot Product (S1 vs S3) [Same Context]:      4

 KEY INSIGHT:
   BoW assigns identical weight to 'light' in all sentences.
   It cannot distinguish 'light' (illumination) from
   'light' (low-calorie) — proving the Polysemy Barrier.

 Static count vectors fail to capture word meaning in context.


Theory and Reflection Questions:

1. The Vector Conflict:
When I ran the dot product, I noticed that Sentence 1 and Sentence  two got a non-zero similarity score even though "light" means completely different things in each. This is because CountVectorizer just counts how many times a word appears, it has no idea what the word actually means in that sentence. So whether "light" refers to calories or to actual light coming through a box, the model treats it as the exact same thing. That's the core problem with static vectors.

2. The Context Blindspot:
The biggest issue with Bag-of-Words is that it completely throws away the meaning behind words. Imagine searching "light snack" on a website a BoW-based search engine could easily return results about light bulbs just because the word "light" appears. The same problem hits chatbots, which could misunderstand what a user is actually asking. Once you convert text into word counts, all the context and real meaning is just gone.

3.The Gen-AI Architectural Fix:
This is exactly the problem that modern LLMs like GPT solve using Self-Attention. Instead of giving "light" one fixed vector forever, the model looks at all the surrounding words and builds a meaning based on context. So "light" next to "stomach" gets a totally different vector than "light" next to "box." That's how Context-Aware Embeddings work the same word gets a different mathematical identity depending on where it appears.

# New Section